name: "{code}bridge"
markdown: redcarpet
pygments: true

navigation:
- text: Home
  url: /index.htm
- text: Directions
  url: /directions.htm
- text: Calendar
  url: /calendar.htm

permalink: /:categories/:year-:month-:day/:title.htm
