# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Codebridge
description:
url: https://codebridge.org.za

title: Codebridge
email:
url: https://codebridge.org.za
description: "A community of people who want to do good things with data and technology"
twitter:
  username: codebridge-za
logo: /img/logo.png

collections:
  tools:
    output: true
  team:
    output: true
  articles:
    output: true
  types:
    output: true
    permalink: /articles/:name.html
  themes:
    output: true
  academy:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image:

sass:
  style: compressed

# Build settings
markdown: kramdown
exclude: [vendor]

gems:
  - jekyll-sitemap